name: Publish to NPM
description: Publish package to NPM with automatic version generation and idempotent checks

runs:
  using: composite
  steps:
    - name: Setup Node.js with npm 11+ (for trusted publishing)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Generate unique version from git
      id: version
      shell: bash
      run: |
        # Get base version from package.json
        BASE_VERSION=$(jq -r .version package.json)

        # Auto-detect if this is a tag or branch push
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          IS_TAG=true
          # For tags, use the base version as-is (stable release)
          NPM_VERSION="${BASE_VERSION}"
          NPM_TAG="latest"
          echo "📦 Publishing stable release: ${NPM_VERSION}"
          echo "   Trigger: Tag ${GITHUB_REF#refs/tags/}"
        else
          IS_TAG=false
          # For main branch, create a pre-release version using git describe
          # Format: 0.3.0-next.5.g1a2b3c4 (base-next.commits.hash)
          GIT_COMMIT=$(git rev-parse --short HEAD)
          COMMITS_SINCE_TAG=$(git rev-list --count HEAD ^$(git describe --tags --abbrev=0 2>/dev/null || echo HEAD) 2>/dev/null || echo "0")
          NPM_VERSION="${BASE_VERSION}-next.${COMMITS_SINCE_TAG}.g${GIT_COMMIT}"
          NPM_TAG="next"
          echo "🚧 Publishing pre-release: ${NPM_VERSION}"
          echo "   Trigger: Branch ${GITHUB_REF#refs/heads/}"
        fi

        echo "version=${NPM_VERSION}" >> $GITHUB_OUTPUT
        echo "tag=${NPM_TAG}" >> $GITHUB_OUTPUT
        echo "is_tag=${IS_TAG}" >> $GITHUB_OUTPUT

        # Update package.json with the new version
        node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('package.json')); pkg.version = '${NPM_VERSION}'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');"

        echo "Updated package.json to version ${NPM_VERSION}"

    - name: Validate tag matches package.json version
      if: steps.version.outputs.is_tag == 'true'
      shell: bash
      run: |
        # Extract version from package.json
        PKG_VERSION=$(jq -r .version package.json)

        # Extract version from git tag (strip 'v' prefix)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}

        echo "Package version: $PKG_VERSION"
        echo "Tag version: $TAG_VERSION"

        if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
          echo "❌ Error: Version mismatch!"
          echo "   package.json version: $PKG_VERSION"
          echo "   Git tag version: $TAG_VERSION"
          echo ""
          echo "Please ensure the git tag matches the version in package.json"
          exit 1
        fi

        echo "✅ Version validation passed: $PKG_VERSION"

    - name: Check if version exists
      id: check-exists
      shell: bash
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        VERSION="${{ steps.version.outputs.version }}"

        if npm view "${PACKAGE_NAME}@${VERSION}" version &>/dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Version ${VERSION} already exists on npm"
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Version ${VERSION} does not exist, will publish"
        fi

    - name: Publish to npm (with OIDC trusted publishing)
      if: steps.check-exists.outputs.exists == 'false'
      shell: bash
      run: npm publish --tag ${{ steps.version.outputs.tag }} --provenance --access public

    - name: Update dist-tag (version already exists)
      if: steps.check-exists.outputs.exists == 'true' && steps.version.outputs.is_tag == 'true'
      shell: bash
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        VERSION="${{ steps.version.outputs.version }}"
        TAG="${{ steps.version.outputs.tag }}"

        echo "Version ${VERSION} already published, updating dist-tag to ${TAG}"
        npm dist-tag add "${PACKAGE_NAME}@${VERSION}" "${TAG}"

    - name: Skip (pre-release already exists)
      if: steps.check-exists.outputs.exists == 'true' && steps.version.outputs.is_tag != 'true'
      shell: bash
      run: |
        echo "⏭️ Pre-release version already exists, skipping"
